# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CAS_small_4.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(323, 201)
        MainWindow.setMinimumSize(QSize(323, 180))
        MainWindow.setMaximumSize(QSize(323, 201))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setMinimumSize(QSize(323, 180))
        self.centralwidget.setMaximumSize(QSize(323, 180))
        self.centralwidget.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 323, 180))
        self.frame.setStyleSheet(u"background-color: rgb(84, 84, 84);")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_2 = QFrame(self.frame)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(5, 0, 253, 180))
        self.frame_2.setStyleSheet(u"background-color: rgb(0, 0, 0);")
        self.frame_2.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Shadow.Raised)
        self.Line1 = QLabel(self.frame_2)
        self.Line1.setObjectName(u"Line1")
        self.Line1.setGeometry(QRect(0, 0, 253, 18))
        font = QFont()
        font.setFamilies([u"Arial"])
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(False)
        self.Line1.setFont(font)
        self.Line1.setStyleSheet(u"")
        self.Line2 = QLabel(self.frame_2)
        self.Line2.setObjectName(u"Line2")
        self.Line2.setGeometry(QRect(0, 18, 253, 18))
        self.Line2.setFont(font)
        self.Line2.setStyleSheet(u"")
        self.Line3 = QLabel(self.frame_2)
        self.Line3.setObjectName(u"Line3")
        self.Line3.setGeometry(QRect(0, 36, 253, 18))
        self.Line3.setFont(font)
        self.Line3.setStyleSheet(u"")
        self.Line4 = QLabel(self.frame_2)
        self.Line4.setObjectName(u"Line4")
        self.Line4.setGeometry(QRect(0, 54, 253, 18))
        self.Line4.setFont(font)
        self.Line4.setStyleSheet(u"")
        self.Line5 = QLabel(self.frame_2)
        self.Line5.setObjectName(u"Line5")
        self.Line5.setGeometry(QRect(0, 72, 253, 18))
        self.Line5.setFont(font)
        self.Line5.setStyleSheet(u"")
        self.Line6 = QLabel(self.frame_2)
        self.Line6.setObjectName(u"Line6")
        self.Line6.setGeometry(QRect(0, 90, 253, 18))
        self.Line6.setFont(font)
        self.Line6.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.Line6.setStyleSheet(u"")
        self.Line6.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.Line7 = QLabel(self.frame_2)
        self.Line7.setObjectName(u"Line7")
        self.Line7.setGeometry(QRect(0, 108, 253, 18))
        self.Line7.setFont(font)
        self.Line7.setStyleSheet(u"")
        self.Line8 = QLabel(self.frame_2)
        self.Line8.setObjectName(u"Line8")
        self.Line8.setGeometry(QRect(0, 126, 253, 18))
        self.Line8.setFont(font)
        self.Line8.setStyleSheet(u"")
        self.Line9 = QLabel(self.frame_2)
        self.Line9.setObjectName(u"Line9")
        self.Line9.setGeometry(QRect(0, 144, 253, 18))
        self.Line9.setFont(font)
        self.Line9.setStyleSheet(u"")
        self.Line10 = QLabel(self.frame_2)
        self.Line10.setObjectName(u"Line10")
        self.Line10.setGeometry(QRect(0, 162, 253, 18))
        self.Line10.setFont(font)
        self.Line10.setStyleSheet(u"")
        self.blue_arrow = QLabel(self.frame)
        self.blue_arrow.setObjectName(u"blue_arrow")
        self.blue_arrow.setGeometry(QRect(285, 113, 18, 20))
        self.blue_arrow.setStyleSheet(u"")
        self.blue_arrow.setLineWidth(11)
        self.blue_arrow.setTextFormat(Qt.TextFormat.MarkdownText)
        self.blue_arrow.setPixmap(QPixmap(u"../../../arrow_newnewnew.png"))
        self.blue_arrow.setWordWrap(True)
        self.amber_mssgs_down_count = QLabel(self.frame)
        self.amber_mssgs_down_count.setObjectName(u"amber_mssgs_down_count")
        self.amber_mssgs_down_count.setGeometry(QRect(274, 134, 40, 23))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setStrikeOut(False)
        self.amber_mssgs_down_count.setFont(font1)
        self.amber_mssgs_down_count.setStyleSheet(u"color: rgb(254, 203, 0);\n"
"\n"
"")
        self.amber_mssgs_down_count.setIndent(4)
        self.white_mssgs_down_count = QLabel(self.frame)
        self.white_mssgs_down_count.setObjectName(u"white_mssgs_down_count")
        self.white_mssgs_down_count.setGeometry(QRect(274, 89, 40, 23))
        font2 = QFont()
        font2.setFamilies([u"Arial"])
        font2.setPointSize(12)
        font2.setBold(True)
        self.white_mssgs_down_count.setFont(font2)
        self.white_mssgs_down_count.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.white_mssgs_down_count.setIndent(4)
        self.white_mssgs_up_count = QLabel(self.frame)
        self.white_mssgs_up_count.setObjectName(u"white_mssgs_up_count")
        self.white_mssgs_up_count.setGeometry(QRect(274, 157, 40, 23))
        self.white_mssgs_up_count.setFont(font2)
        self.white_mssgs_up_count.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"")
        self.white_mssgs_up_count.setIndent(4)
        self.amber_mssgs_up_count = QLabel(self.frame)
        self.amber_mssgs_up_count.setObjectName(u"amber_mssgs_up_count")
        self.amber_mssgs_up_count.setGeometry(QRect(274, 66, 40, 23))
        self.amber_mssgs_up_count.setFont(font2)
        self.amber_mssgs_up_count.setStyleSheet(u"color: rgb(254, 203, 0);\n"
"\n"
"")
        self.amber_mssgs_up_count.setMidLineWidth(1)
        self.amber_mssgs_up_count.setIndent(4)
        self.arrow_white_down = QLabel(self.frame)
        self.arrow_white_down.setObjectName(u"arrow_white_down")
        self.arrow_white_down.setGeometry(QRect(300, 165, 11, 9))
        self.arrow_white_down.setPixmap(QPixmap(u"white_arrow_down.png"))
        self.arrow_amber_down = QLabel(self.frame)
        self.arrow_amber_down.setObjectName(u"arrow_amber_down")
        self.arrow_amber_down.setGeometry(QRect(300, 142, 11, 9))
        self.arrow_amber_down.setStyleSheet(u"")
        self.arrow_amber_down.setPixmap(QPixmap(u"amber_arrow_down.png"))
        self.arrow_white_up = QLabel(self.frame)
        self.arrow_white_up.setObjectName(u"arrow_white_up")
        self.arrow_white_up.setGeometry(QRect(300, 95, 11, 9))
        self.arrow_white_up.setPixmap(QPixmap(u"white_arrow_up.png"))
        self.arrow_amber_up = QLabel(self.frame)
        self.arrow_amber_up.setObjectName(u"arrow_amber_up")
        self.arrow_amber_up.setGeometry(QRect(300, 72, 11, 9))
        self.arrow_amber_up.setStyleSheet(u"")
        self.arrow_amber_up.setPixmap(QPixmap(u"amber_arrow_up.png"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Line1.setText("")
        self.Line2.setText("")
        self.Line3.setText("")
        self.Line4.setText("")
        self.Line5.setText("")
        self.Line6.setText("")
        self.Line7.setText("")
        self.Line8.setText("")
        self.Line9.setText(QCoreApplication.translate("MainWindow", u"Hello", None))
        self.Line10.setText("")
        self.blue_arrow.setText("")
        self.amber_mssgs_down_count.setText(QCoreApplication.translate("MainWindow", u"03", None))
        self.white_mssgs_down_count.setText(QCoreApplication.translate("MainWindow", u"03", None))
        self.white_mssgs_up_count.setText(QCoreApplication.translate("MainWindow", u"03", None))
        self.amber_mssgs_up_count.setText(QCoreApplication.translate("MainWindow", u"03", None))
        self.arrow_white_down.setText("")
        self.arrow_amber_down.setText("")
        self.arrow_white_up.setText("")
        self.arrow_amber_up.setText("")
    # retranslateUi

